name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up qemu
      uses: docker/setup-qemu-action@v2

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag llama2-chinese-7b-gradio:$(date +%s)
      
      
    - name: Build and push docker image
      uses: docker/build-push-action@v4
      with:
        context: ./docker/
        platforms: linux/amd64,linux/arm64
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/llama2-chinese-7b-gradio:latest
